# Để thành false nếu cảm thấy server lag
async: true

admin-permission: "lootclear.admin"

# Những thế giới được áp dụng
world-apply:
  - "world"

# Những loại rương để xóa vật phẩm
apply-to:
  - "CHEST"
  - "TRAPPED_CHEST"
  - "STORAGE_MINECART"
  - "WHITE_SHULKER_BOX"
  - "ORANGE_SHULKER_BOX"
  - "MAGENTA_SHULKER_BOX"
  - "LIGHT_BLUE_SHULKER_BOX"
  - "YELLOW_SHULKER_BOX"
  - "LIME_SHULKER_BOX"
  - "PINK_SHULKER_BOX"
  - "GRAY_SHULKER_BOX"
  - "LIGHT_GRAY_SHULKER_BOX"
  - "CYAN_SHULKER_BOX"
  - "PURPLE_SHULKER_BOX"
  - "BLUE_SHULKER_BOX"
  - "BROWN_SHULKER_BOX"
  - "GREEN_SHULKER_BOX"
  - "RED_SHULKER_BOX"
  - "BLACK_SHULKER_BOX"

# Những vật phẩm dùng để xóa
items:
  - "CHAINMAIL_HELMET"
  - "DIAMOND_HELMET"
  - "GOLD_HELMET"
  - "IRON_HELMET"
  - "LEATHER_HELMET"
  - "CHAINMAIL_CHESTPLATE"
  - "DIAMOND_CHESTPLATE"
  - "GOLD_CHESTPLATE"
  - "IRON_CHESTPLATE"
  - "LEATHER_CHESTPLATE"
  - "CHAINMAIL_LEGGINGS"
  - "DIAMOND_LEGGINGS"
  - "GOLD_LEGGINGS"
  - "IRON_LEGGINGS"
  - "LEATHER_LEGGINGS"
  - "CHAINMAIL_BOOTS"
  - "DIAMOND_BOOTS"
  - "GOLD_BOOTS"
  - "IRON_BOOTS"
  - "LEATHER_BOOTS"
  - "DIAMOND_SWORD"
  - "GOLD_SWORD"
  - "STONE_SWORD"
  - "IRON_SWORD"
  - "WOOD_SWORD"