# Để thành false nếu cảm thấy server lag
async: true

admin-permission: "lootclear.admin"

# Những thế giới được áp dụng
world-apply:
  - "world"

# Những loại rương để xóa vật phẩm
apply-to:
  - "CHEST"
  - "TRAPPED_CHEST"
  - "CHEST_MINECART"
  - "ACACIA_CHEST_BOAT"
  - "BIRCH_CHEST_BOAT"
  - "DARK_OAK_CHEST_BOAT"
  - "JUNGLE_CHEST_BOAT"
  - "MANGROVE_CHEST_BOAT"
  - "OAK_CHEST_BOAT"
  - "SPRUCE_CHEST_BOAT"
  - "SHULKER_BOX"
  - "WHITE_SHULKER_BOX"
  - "ORANGE_SHULKER_BOX"
  - "MAGENTA_SHULKER_BOX"
  - "LIGHT_BLUE_SHULKER_BOX"
  - "YELLOW_SHULKER_BOX"
  - "LIME_SHULKER_BOX"
  - "PINK_SHULKER_BOX"
  - "GRAY_SHULKER_BOX"
  - "LIGHT_GRAY_SHULKER_BOX"
  - "CYAN_SHULKER_BOX"
  - "PURPLE_SHULKER_BOX"
  - "BLUE_SHULKER_BOX"
  - "BROWN_SHULKER_BOX"
  - "GREEN_SHULKER_BOX"
  - "RED_SHULKER_BOX"
  - "BLACK_SHULKER_BOX"

# Những vật phẩm dùng để xóa
items:
  - "CHAINMAIL_HELMET"
  - "DIAMOND_HELMET"
  - "GOLDEN_HELMET"
  - "IRON_HELMET"
  - "LEATHER_HELMET"
  - "TURTLE_HELMET"
  - "NETHERITE_HELMET"
  - "CHAINMAIL_CHESTPLATE"
  - "DIAMOND_CHESTPLATE"
  - "GOLDEN_CHESTPLATE"
  - "IRON_CHESTPLATE"
  - "LEATHER_CHESTPLATE"
  - "NETHERITE_CHESTPLATE"
  - "CHAINMAIL_LEGGINGS"
  - "DIAMOND_LEGGINGS"
  - "GOLDEN_LEGGINGS"
  - "IRON_LEGGINGS"
  - "LEATHER_LEGGINGS"
  - "NETHERITE_LEGGINGS"
  - "CHAINMAIL_BOOTS"
  - "DIAMOND_BOOTS"
  - "GOLDEN_BOOTS"
  - "IRON_BOOTS"
  - "LEATHER_BOOTS"
  - "NETHERITE_BOOTS"
  - "DIAMOND_SWORD"
  - "GOLDEN_SWORD"
  - "STONE_SWORD"
  - "IRON_SWORD"
  - "NETHERITE_SWORD"
  - "WOODEN_SWORD"